# Beats "nightly" build artifacts.
# Published by: https://beats-ci.elastic.co/job/elastic+beats+master+package/
url_base: https://s3-us-west-2.amazonaws.com/beats-package-snapshots
version: 7.0.0-alpha1-SNAPSHOT
