---
- name: Packaging tests Packetbeat
  hosts:
    - debian
    - centos
    - darwin
  sudo: yes
  tags:
    - packetbeat
  vars:
    - beat_name: packetbeat
  roles:
    - common
    - test-install
    - test-packetbeat-file
    - test-uninstall
    - {role: test-linux-binary, when: ansible_system == "Linux"}


- name: Packaging tests Topbeat
  hosts:
    - debian
    - centos
    - darwin
  sudo: yes
  tags:
    - topbeat
  vars:
    - beat_name: topbeat
  roles:
    - common
    - test-install
    - test-topbeat-file
    - test-uninstall
    - {role: test-linux-binary, when: ansible_system == "Linux"}

- name: Packaging tests Filebeat
  hosts:
    - debian
    - centos
    - darwin
  sudo: yes
  tags:
    - filebeat
  vars:
    - beat_name: filebeat
  roles:
    - common
    - test-install
    - test-filebeat-file
    - test-uninstall
    - {role: test-linux-binary, when: ansible_system == "Linux"}

# windows
- name: Packaging windows tests for Packetbeat
  hosts:
    - windows
  tags:
    - packetbeat
    - windows
  vars:
    - beat_name: packetbeat
  roles:
    - common
    - test-install
    - test-win-packetbeat-file
    - test-uninstall

- name: Packaging windows tests for Topbeat
  hosts:
    - windows
  tags:
    - topbeat
    - windows
  vars:
    - beat_name: topbeat
  roles:
    - common
    - test-install
    - test-win-topbeat-file
    - test-uninstall

- name: Packaging windows tests for Filebeat
  hosts:
    - windows
  tags:
    - filebeat
    - windows
  vars:
    - beat_name: filebeat
  roles:
    - common
    - test-install
    - test-win-filebeat-file
    - test-uninstall
