---

- name: Assert Winlogbeat output event
  win_shell: 'cat -Encoding UTF8 {{ beat_output_file }} | select -First 1'
  register: wlb_json

- set_fact:
    wlb_event: '{{ wlb_json.stdout | from_json }}'

- debug:
    var: wlb_event

- assert:
    that:
      - "'@timestamp' in wlb_event"
      - "'log_name' in wlb_event"
      - "'source_name' in wlb_event"
      - "'computer_name' in wlb_event"
      - "'type' in wlb_event"
      - "'record_number' in wlb_event"
      - "'event_id' in wlb_event"
      - "'level' in wlb_event"

- name: Assert Winlogbeat registry contents
  win_shell: 'cat -Encoding UTF8 {{ beat_registry_file }}'
  register: wlb_registry_output

- set_fact:
    wlb_registry: '{{ wlb_registry_output.stdout | from_yaml }}'

- debug:
    var: wlb_registry

- assert:
    that:
      - "'update_time' in wlb_registry"
      - "'event_logs' in wlb_registry"
