---

- name: Delete logs directory
  win_file:
    path: '{{ filebeat_logs_dir }}'
    state: absent
  when: ansible_system == "Win32NT"

- name: Create logs directory
  win_file:
    path: '{{ filebeat_logs_dir }}'
    state: directory
  when: ansible_system == "Win32NT"

- name: Create log file
  win_copy:
    src: '{{ role_path }}/files/filebeat-test.log'
    dest: '{{ filebeat_logs_dir }}\test.log'
  when: ansible_system == "Win32NT"

- name: Delete logs directory
  file:
    path: '{{ filebeat_logs_dir }}'
    state: absent
  when: ansible_system != "Win32NT"

- name: Create logs directory
  file:
    path: '{{ filebeat_logs_dir }}'
    state: directory
  when: ansible_system != "Win32NT"

- name: Create log file
  copy:
    src: '{{ role_path }}/files/filebeat-test.log'
    dest: '{{ filebeat_logs_dir }}/test.log'
  when: ansible_system != "Win32NT"
