
- name: Download package sha1
  get_url: url={{beat_url}}.sha1.txt dest={{workdir}} validate_certs=no
  register: sha1_file

- name: Download package
  get_url: url={{beat_url}} dest={{workdir}} validate_certs=no
  when: sha1_file.changed

- name: Check file (linux)
  shell: chdir={{workdir}} sha1sum -c {{beat_pkg}}.sha1.txt
  when: ansible_os_family in ["RedHat", "Debian"] and sha1_file.changed

- name: Check file (darwin)
  shell: chdir={{workdir}} shasum -c {{beat_pkg}}.sha1.txt
  when: ansible_os_family == "Darwin" and sha1_file.changed
